version: '3.8'
services:
  spring-boot-monitoring:
    build: .
    ports:
      - "8080:8080"
    networks:
      - monitoring
    depends_on:
      - prometheus
      - grafana
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring
    volumes:
      - ./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

networks:
  monitoring:
    driver: bridge
